language: python
python:
  - '2.7'
  - '3.2'
  - '3.4'
  - '3.5'
  - '3.6'

install: 'pip install -r requirements/testing.txt'
script: coverage run --source=pwapt -m unittest discover
after_success:
  - codecov
