language: python
python:
  - '2.7'
  - '3.2'
  - '3.4'
  - '3.5'
  - '3.6'

install: 'pip install -r requirements/testing.txt'
script: if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then coverage run --source=pwapt -m unittest discover; fi
after_success:
  - codecov
